In [66]:
import numpy as np
import pandas as pd
from sklearn import linear_model 
import matplotlib.pyplot as plt
#%matplotlib.inline

In [67]:
a=pd.read_csv('iris.csv')
a

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
5             5.4          3.9           1.7          0.4     Setosa
6             4.6          3.4           1.4          0.3     Setosa
7             5.0          3.4           1.5          0.2     Setosa
8             4.4          2.9           1.4          0.2     Setosa
9             4.9          3.1           1.5          0.1     Setosa
10            5.4          3.7           1.5          0.2     Setosa
11            4.8          3.4           1.6          0.2     Setosa
12            4.8          3.0           1.4          0.1     Setosa
13            4.3          3.0           1.1          0.1     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
16            5.4          3.9           1.3          0.4     Setosa
17            5.1          3.5           1.4          0.3     Setosa
18            5.7          3.8           1.7          0.3     Setosa
19            5.1          3.8           1.5          0.3     Setosa
20            5.4          3.4           1.7          0.2     Setosa
21            5.1          3.7           1.5          0.4     Setosa
22            4.6          3.6           1.0          0.2     Setosa
23            5.1          3.3           1.7          0.5     Setosa
24            4.8          3.4           1.9          0.2     Setosa
25            5.0          3.0           1.6          0.2     Setosa
26            5.0          3.4           1.6          0.4     Setosa
27            5.2          3.5           1.5          0.2     Setosa
28            5.2          3.4           1.4          0.2     Setosa
29            4.7          3.2           1.6          0.2     Setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  Virginica
121           5.6          2.8           4.9          2.0  Virginica
122           7.7          2.8           6.7          2.0  Virginica
123           6.3          2.7           4.9          1.8  Virginica
124           6.7          3.3           5.7          2.1  Virginica
125           7.2          3.2           6.0          1.8  Virginica
126           6.2          2.8           4.8          1.8  Virginica
127           6.1          3.0           4.9          1.8  Virginica
128           6.4          2.8           5.6          2.1  Virginica
129           7.2          3.0           5.8          1.6  Virginica
130           7.4          2.8           6.1          1.9  Virginica
131           7.9          3.8           6.4          2.0  Virginica
132           6.4          2.8           5.6          2.2  Virginica
133           6.3          2.8           5.1          1.5  Virginica
134           6.1          2.6           5.6          1.4  Virginica
135           7.7          3.0           6.1          2.3  Virginica
136           6.3          3.4           5.6          2.4  Virginica
137           6.4          3.1           5.5          1.8  Virginica
138           6.0          3.0           4.8          1.8  Virginica
139           6.9          3.1           5.4          2.1  Virginica
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [68]:
a.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [69]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal.length    150 non-null float64
sepal.width     150 non-null float64
petal.length    150 non-null float64
petal.width     150 non-null float64
variety         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [70]:
print(a.max(),a.min(),a.var(),a.std(),a.mean(),a.median())

sepal.length          7.9
sepal.width           4.4
petal.length          6.9
petal.width           2.5
variety         Virginica
dtype: object sepal.length       4.3
sepal.width          2
petal.length         1
petal.width        0.1
variety         Setosa
dtype: object sepal.length    0.685694
sepal.width     0.189979
petal.length    3.116278
petal.width     0.581006
dtype: float64 sepal.length    0.828066
sepal.width     0.435866
petal.length    1.765298
petal.width     0.762238
dtype: float64 sepal.length    5.843333
sepal.width     3.057333
petal.length    3.758000
petal.width     1.199333
dtype: float64 sepal.length    5.80
sepal.width     3.00
petal.length    4.35
petal.width     1.30
dtype: float64

In [71]:
a.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [72]:
a.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [73]:
#b=pd.DataFrame(a)
#b

In [74]:
#type(b)

In [75]:
#r=b.rename(index=str, columns={"5.1": "Sepal_width", "3.5": "Sepal_length","1.4":"Petal_width","0.2":"Petal_length"})

In [76]:
#r.head()

In [77]:
#r.ffill()

In [78]:
#import matplotlib.pyplot as plt
#plt.scatter

In [79]:
a.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train,X_test,y_train,y_test=train_test_split(a[['sepal.length']],a.variety,train_size=0.9)

In [82]:
X_test

     sepal.length
7             5.0
105           7.6
114           5.8
111           6.4
81            5.5
50            7.0
65            6.7
63            6.1
108           6.7
125           7.2
0             5.1
24            4.8
117           7.7
38            4.4
53            5.5

In [83]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [84]:
model.fit(X_train,y_train)

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [85]:
X_test

     sepal.length
7             5.0
105           7.6
114           5.8
111           6.4
81            5.5
50            7.0
65            6.7
63            6.1
108           6.7
125           7.2
0             5.1
24            4.8
117           7.7
38            4.4
53            5.5

In [86]:
y_predicted=model.predict(X_test)

In [87]:
model.predict_proba(X_test)

array([[0.42962087, 0.3232541 , 0.24712503],
       [0.08964709, 0.33862638, 0.57172653],
       [0.30364419, 0.34438933, 0.35196649],
       [0.214604  , 0.35092958, 0.43446642],
       [0.35128507, 0.33776346, 0.31095147],
       [0.14209336, 0.34819696, 0.50970968],
       [0.17588674, 0.35062728, 0.47348597],
       [0.25757468, 0.34885696, 0.39356836],
       [0.17588674, 0.35062728, 0.47348597],
       [0.12241107, 0.34558897, 0.53199996],
       [0.41433767, 0.32639718, 0.25926515],
       [0.45925584, 0.31677496, 0.2239692 ],
       [0.08274207, 0.33662417, 0.58063376],
       [0.51376769, 0.30367387, 0.18255845],
       [0.35128507, 0.33776346, 0.31095147]])

In [88]:
model.score(X_test,y_test)

0.6666666666666666

In [89]:
X_test

     sepal.length
7             5.0
105           7.6
114           5.8
111           6.4
81            5.5
50            7.0
65            6.7
63            6.1
108           6.7
125           7.2
0             5.1
24            4.8
117           7.7
38            4.4
53            5.5

In [90]:
model.predict(X_test)

array(['Setosa', 'Virginica', 'Virginica', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Virginica', 'Virginica', 'Virginica',
       'Setosa', 'Setosa', 'Virginica', 'Setosa', 'Setosa'], dtype=object)

# Multiple LOgistic regression

In [91]:
from sklearn import datasets

In [92]:
Data= datasets.load_iris()

In [100]:
s=Data.data[0]

In [94]:
Data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [95]:
Data.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...'

In [96]:
Data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [97]:
from sklearn.model_selection import train_test_split

In [110]:
X_train,X_test,y_train,y_test=train_test_split(a[s],a.variety,train_size=0.9)

KeyError: "None of [Float64Index([5.1, 3.5, 1.4, 0.2], dtype='float64')] are in the [columns]"

In [99]:
X_test

     sepal.length
69            5.6
146           6.3
113           5.7
130           7.4
84            5.4
43            5.0
75            6.6
11            4.8
61            5.9
13            4.3
1             4.9
98            5.1
115           6.4
21            5.1
18            5.7

In [105]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [104]:
model.fit(X_train,y_train)

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [103]:
X_test

     sepal.length
71            6.1
50            7.0
141           6.9
36            5.5
82            5.8
67            5.8
15            5.7
22            4.6
133           6.3
75            6.6
70            5.9
12            4.8
145           6.7
27            5.2
98            5.1

In [106]:
y_predicted=model.predict(X_test)

NotFittedError: This LogisticRegression instance is not fitted yet

In [107]:
model.predict_proba(X_test)

NotFittedError: Call fit before prediction

In [108]:
model.score(X_test,y_test)

NotFittedError: This LogisticRegression instance is not fitted yet

In [109]:
model.predict(X_test)

NotFittedError: This LogisticRegression instance is not fitted yet